apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-native-image-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-native-image-demo
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quarkus-native-image-demo
    spec:
      containers:
      - name: native-image-app
        image: juliuskrah/quarkus-native-rest-demo
        resources:
          limits:
            memory: "20Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
          name: http
      imagePullSecrets:
        - name: nexdock
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-native-image-demo
spec:
  selector:
    app.kubernetes.io/name: quarkus-native-image-demo
  ports:
  - port: 80
    targetPort: http
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: quarkus-native-image-demo
spec:
  prefix: /
  service: quarkus-native-image-demo.development:80
  host: quarkus-native-image-demo.development.gomora.poc.tingg.africa
  timeout_ms: 1000
  connect_timeout_ms: 1000
  idle_timeout_ms: 1000
  